staging:
  cloud_name: "hvy8rylge"
  api_key: "532261557232426"
  api_secret: "9ZZ5-PxaZLAtSLJ1jPGP-8UE-AI"
development:
  cloud_name: "hvy8rylge"
  api_key: "532261557232426"
  api_secret: "9ZZ5-PxaZLAtSLJ1jPGP-8UE-AI"